# Generated by Django 5.0.6 on 2026-05-17 19:51

import apps.materials.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('bachelor', 'Бакалавр'), ('master', 'Магистер'), ('phd', 'Докторат')], default='bachelor', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Emoji or short label', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('semester', models.CharField(blank=True, max_length=50)),
                ('file', models.FileField(upload_to=apps.materials.models.upload_path)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('extension', models.CharField(blank=True, max_length=10)),
                ('extracted_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('uploaded', 'Прикачено'), ('extracting', 'Се обработува'), ('ready', 'Подготвено'), ('failed', 'Неуспешно')], default='uploaded', max_length=20)),
                ('extraction_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='materials.subject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
