# Generated by Django 5.0.6 on 2026-05-18 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['year', 'semester', 'name']},
        ),
        migrations.AddField(
            model_name='material',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Прва година'), (2, 'Втора година'), (3, 'Трета година'), (4, 'Четврта година')], null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, db_index=True, help_text='Универзитетски код (пр. F23L1W004)', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='elective_group',
            field=models.CharField(blank=True, choices=[('F23L1S', 'F23L1S — Изборни (прв циклус)'), ('F23L1W', 'F23L1W — Изборни (зимски)'), ('F23L2S', 'F23L2S — Изборни (втор циклус, летен)'), ('F23L2W', 'F23L2W — Изборни (втор циклус, зимски)'), ('F23L3S', 'F23L3S — Изборни (трет циклус, летен)'), ('F23L3W', 'F23L3W — Изборни (трет циклус, зимски)')], max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='prerequisites',
            field=models.TextField(blank=True, help_text='Предуслови (текст)'),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Прв семестар'), (2, 'Втор семестар'), (3, 'Трет семестар'), (4, 'Четврти семестар'), (5, 'Петти семестар'), (6, 'Шести семестар'), (7, 'Седми семестар'), (8, 'Осми семестар')], help_text='Семестар (1-8)', null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('mandatory', 'Задолжителен'), ('elective', 'Изборен')], default='mandatory', max_length=20),
        ),
        migrations.AddField(
            model_name='subject',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Прва година'), (2, 'Втора година'), (3, 'Трета година'), (4, 'Четврта година')], help_text='Година на студии', null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Прв семестар'), (2, 'Втор семестар'), (3, 'Трет семестар'), (4, 'Четврти семестар'), (5, 'Петти семестар'), (6, 'Шести семестар'), (7, 'Седми семестар'), (8, 'Осми семестар')], null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['year', 'semester'], name='materials_s_year_b29c68_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['subject_type'], name='materials_s_subject_cf4c8c_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['code'], name='materials_s_code_392650_idx'),
        ),
    ]
