# Generated by Django 5.0.6 on 2026-05-19 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_subject_options_material_year_subject_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaterialLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='material',
            name='downloads_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='likes_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='material',
            name='visibility',
            field=models.CharField(choices=[('public', 'Јавно — секој може да го симне'), ('private', 'Приватно — само за мене')], db_index=True, default='public', max_length=20),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['visibility', '-created_at'], name='materials_m_visibil_0fdba5_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['-likes_count'], name='materials_m_likes_c_c22871_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['-downloads_count'], name='materials_m_downloa_ce1dc2_idx'),
        ),
        migrations.AddField(
            model_name='materialdownload',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='materials.material'),
        ),
        migrations.AddField(
            model_name='materialdownload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_downloads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='materiallike',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='materials.material'),
        ),
        migrations.AddField(
            model_name='materiallike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='materialdownload',
            index=models.Index(fields=['material', '-created_at'], name='materials_m_materia_644c55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='materiallike',
            unique_together={('user', 'material')},
        ),
    ]
