# Generated by Django 5.0.6 on 2026-05-17 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('wrong_answer', 'Грешен точен одговор'), ('unclear', 'Нејасно прашање'), ('off_topic', 'Не е поврзано со материјалот'), ('offensive', 'Навредлива содржина'), ('copyright', 'Прекршување авторски права'), ('other', 'Друго')], max_length=30)),
                ('description', models.TextField(max_length=2000)),
                ('status', models.CharField(choices=[('open', 'Отворен'), ('reviewing', 'Се прегледува'), ('resolved', 'Решен'), ('dismissed', 'Отфрлен')], default='open', max_length=20)),
                ('moderator_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_reports', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='quizzes.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='quizzes.quiz')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='moderation__status_282342_idx')],
            },
        ),
    ]
