# Generated by Django 5.0.6 on 2026-05-18 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_subject_options_material_year_subject_code_and_more'),
        ('quizzes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='saves_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='semester',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['-likes_count'], name='quizzes_qui_likes_c_151dbf_idx'),
        ),
        migrations.AddIndex(
            model_name='quiz',
            index=models.Index(fields=['year', 'semester'], name='quizzes_qui_year_5377c1_idx'),
        ),
        migrations.AddField(
            model_name='savedquiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='quizzes.quiz'),
        ),
        migrations.AddField(
            model_name='savedquiz',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='savedquiz',
            unique_together={('user', 'quiz')},
        ),
    ]
