# Generated by Django 5.0.6 on 2026-05-19 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_year',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Тековна година на студии (1-4)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='study_program',
            field=models.CharField(blank=True, help_text='На пр. „Софтверско инженерство и информациски системи"', max_length=100),
        ),
    ]
