# Generated by Django 5.0.6 on 2026-05-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status_emoji',
            field=models.CharField(blank=True, help_text='Опционален emoji за статусот', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='status_label',
            field=models.CharField(blank=True, help_text='Кратки статус-зборови — chilling, study, sleeping...', max_length=50),
        ),
    ]
